version: "3.3"

volumes:
  local_postgres_data:
  local_postgres_data_backups:

services:
  db:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    env_file:
      - ./.envs/.local/.db
    ports:
      - "5432:5432"
  web:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app:z
    ports:
      - "8000:8000"
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.db
#    environment:
#      - POSTGRES_HOST=local
#      - POSTGRES_DB=local
#      - POSTGRES_NAME=local
#      - POSTGRES_USER=local
#      - POSTGRES_PASSWORD=local
    depends_on:
      - db