version: "3.3"

volumes:
  blog_production_postgres_data:
  blog_production_postgres_data_backups:

services:
  nginx:
    image: nginx
    container_name: production_proxy
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    volumes:
      - ./staticfiles:/app/static
      - ./media:/app/media
      - /var/log/containers/:/var/log/nginx
    depends_on:
      - production_web
      - production_es
    networks:
      - backend
    ports:
      - "80:80"
      - "443:443"
    restart: always
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  production_db:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: postgres
#    container_name: content_db
    volumes:
      - blog_production_postgres_data:/var/lib/postgresql/data:Z
      - blog_production_postgres_data_backups:/backups:z
#      - ./.current_db:/init_db
    env_file:
      - ./.envs/.production/.db
    networks:
      - backend
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    shm_size: 2g
    restart: always

  production_es:
    container_name: production_es
    image: elasticsearch:7.8.1
    environment:
      - discovery.type=single-node
    networks:
      - backend
    ports:
      - "9200:9200"

  production_web:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
#    command: gunicorn blog.wsgi:application --bind 0.0.0.0:8000
#    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
#    expose:
#      - "8000"
    volumes:
      - .:/app
#    expose:
#      - 3000
#    ports:
#      - "3000:3000"
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.db
    depends_on:
      - production_db
    command: /startweb
    networks:
      - backend

networks:
    backend:
