# Generated by Django 2.2 on 2022-10-22 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_hotarticles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotarticles',
            name='post',
        ),
        migrations.AddField(
            model_name='hotarticles',
            name='firstpost',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='firstpost', to='blogapp.Post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotarticles',
            name='secondpost',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='secondpost', to='blogapp.Post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotarticles',
            name='thirdpost',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='thirdpost', to='blogapp.Post'),
            preserve_default=False,
        ),
    ]
