# Generated by Django 2.2 on 2022-10-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_auto_20221023_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorprofile',
            name='lastname',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='editorprofile',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='editorprofile',
            name='rank',
            field=models.CharField(choices=[('Redaktor Naczelny', 'Redaktor Naczelny'), ('Redaktor', 'Redaktor'), ('Współpraca', 'Współpraca'), ('Zagraniczny korespondent', 'Zagraniczny korespondent')], default='Redaktor', max_length=20),
        ),
    ]
