# Generated by Django 2.2 on 2022-10-23 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_auto_20221023_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotarticles',
            name='firstpost',
        ),
        migrations.RemoveField(
            model_name='hotarticles',
            name='secondpost',
        ),
        migrations.RemoveField(
            model_name='hotarticles',
            name='thirdpost',
        ),
        migrations.AddField(
            model_name='hotarticles',
            name='first_post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='first_post', to='blogapp.Post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotarticles',
            name='second_post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='second_post', to='blogapp.Post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotarticles',
            name='third_post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='third_post', to='blogapp.Post'),
            preserve_default=False,
        ),
    ]
