# Generated by Django 2.2.10 on 2020-08-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_editorprofile_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='social',
            name='slug',
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=128, unique=True),
        ),
    ]
