# Generated by Django 2.2.10 on 2020-08-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0009_auto_20200819_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=128),
        ),
    ]
