# Generated by Django 2.2 on 2022-11-05 11:01

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogapp', '0009_auto_20221102_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('symbol', models.CharField(max_length=2)),
                ('short_description', models.CharField(default='', max_length=200)),
                ('image', models.ImageField(default='', upload_to='')),
                ('slug', models.SlugField(blank=True, max_length=128, null=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('clicks', models.IntegerField(default=0)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('publish_on', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.Category')),
                ('tags', models.ManyToManyField(blank=True, to='blogapp.Tag')),
            ],
        ),
        migrations.RenameModel(
            old_name='Poster',
            new_name='Schedule',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blogapp.Article'),
        ),
        migrations.AlterField(
            model_name='hotarticles',
            name='first_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_post', to='blogapp.Article'),
        ),
        migrations.AlterField(
            model_name='hotarticles',
            name='second_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_post', to='blogapp.Article'),
        ),
        migrations.AlterField(
            model_name='hotarticles',
            name='third_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_post', to='blogapp.Article'),
        ),
        migrations.DeleteModel(
            name='MainNews',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
