# Generated by Django 2.2 on 2022-11-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0011_auto_20221105_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='show_in_main_news',
            field=models.BooleanField(default=True),
        ),
    ]
