# Generated by Django 2.2 on 2022-11-06 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0012_article_show_in_main_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='short_description',
        ),
    ]
