# Generated by Django 2.2.10 on 2020-08-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0013_post_content2'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorprofile',
            name='slug',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
