# Generated by Django 2.2 on 2022-11-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0013_remove_article_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='clicks',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
