# Generated by Django 2.2.10 on 2020-09-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0017_auto_20200917_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorprofile',
            name='lastname',
            field=models.CharField(default='redakcyjny', max_length=30),
        ),
        migrations.AddField(
            model_name='editorprofile',
            name='name',
            field=models.CharField(default='dział', max_length=30),
        ),
    ]
