# Generated by Django 2.2.10 on 2020-09-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0019_auto_20200924_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
    ]
