# Generated by Django 2.2.10 on 2021-03-13 11:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0021_auto_20201001_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', upload_to='')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
