# Generated by Django 2.2.10 on 2021-03-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0023_mainnews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainnews',
            name='post',
        ),
        migrations.AddField(
            model_name='mainnews',
            name='post',
            field=models.ManyToManyField(related_name='posts', to='blogapp.Post'),
        ),
    ]
