name: Blog Workflow

on:
  pull_request:
    branches:
      - new_changes
  push:
    branches:
      - new_changes

jobs:


  basic-health-job:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: test
#          POSTGRES_HOST: db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
#        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v3
#      - uses: isbang/compose-action@v1.4.1
#        with:
#          compose-file: "./local.yml"
#        env:
#          SECRET_KEY: 'asdsadhuiu1247hyfewh7'
#      - name: Check tests
#        env:
#          SECRET_KEY: 'asdsadhuiu1247hyfewh7'
#        run: |
##          docker-compose -f local.yml run web python manage.py makemigrations
##          docker-compose -f local.yml run web python manage.py migrate
#          docker-compose -f local.yml run web python -m pytest

      - name: Install apt dependencies
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y
          sudo apt-get install pandoc
      - name: Setup python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
#
      - name: Setup pip
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade --upgrade-strategy eager -r ./requirements/base.txt
#
#      - name: Check Migrations
#        env:
#          USE_DOCKER: true
#        run: |
#          python manage.py makemigrations --check --dry-run
##
##      - name: Run migrations
##        env:
##          USE_DOCKER: true
##          DJANGO_SETTINGS_MODULE: config.settings.local_gold
##        run: |
##          export DEBUG=0
##          export GITHUB_WORKFLOW=True
##          export MODE=workflow
##          python manage.py migrate
#
#      - name: Django Check
#        env:
#          SECRET_KEY: 'asdsadhuiu1247hyfewh7'
#          USE_DOCKER: true
#        run: |
#          export DEBUG=0
#          export GITHUB_WORKFLOW=True
#          export MODE=workflow
#          python manage.py check
#
      - name: Django Tests
        env:
          SECRET_KEY: 'asdsadhuiu1247hyfewh7'
          TEST_KEY: 'TEST_KEYsadasdas'
          DJANGO_SETTINGS_MODULE: 'blog.config.settings.local'
          POSTGRES_DB: postgres
          POSTGRES_HOST: localhost
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: test
          POSTGRES_PORT: 5432
        run: |
          python -m pytest
  

  deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    needs: basic-health-job
    steps:
      - name: multiple SSH commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: ${{ secrets.SERVER_PORT }}
          password: ${{secrets.SERVER_PASSWORD}}
          script: |
            cd Blog
            git pull
#            docker-compose -f production.yml up
          
